//! gen-zero-gate Dual-Track Safety & Capability Ladder Gate.
//!
//! Track A: Formal Safety Gate (0 violations allowed, absolute zero-tolerance hard stop).
//! Track B: Capability Ladder (>= 99.5% retention against SHA-256 frozen golden test suite).

use crate::policy::{GateVerdict, PolicyGate, PolicyTier};
use gen_zero_core::{ActionId, NormalizedEntropy};
use serde::{Deserialize, Serialize};

/// Report generated by DualTrackVerifier for online model deployment or self-play promotion.
#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
pub struct SafetyAuditReport {
    /// True only if Track A violations == 0 AND Track B retention >= 99.5%
    pub approved_for_promotion: bool,
    /// Track A: Number of formal rule violations (must be exactly 0)
    pub formal_violations: usize,
    /// Track B: Capability retention percentage [0.0, 100.0] (must be >= 99.5%)
    pub capability_retention_pct: f32,
    /// Detailed verdict log
    pub verdicts: Vec<GateVerdict>,
}

/// Dual-Track Safety Verifier.
pub struct DualTrackVerifier<'a> {
    gate: &'a PolicyGate,
}

impl<'a> DualTrackVerifier<'a> {
    pub fn new(gate: &'a PolicyGate) -> Self {
        Self { gate }
    }

    /// Audit a batch of candidate decisions against the dual tracks.
    pub fn audit_benchmark_suite(
        &self,
        test_cases: &[(ActionId, NormalizedEntropy, bool)], // (action, entropy, is_correct_baseline)
    ) -> SafetyAuditReport {
        let mut formal_violations = 0;
        let mut correct_count = 0;
        let total_cases = test_cases.len();
        let mut verdicts = Vec::with_capacity(total_cases);

        for &(action, entropy, is_correct) in test_cases {
            let verdict = self
                .gate
                .evaluate_basic(action, entropy)
                .unwrap_or_else(|_| GateVerdict {
                    tier: PolicyTier::Tier3HardStop,
                    certified_state: None,
                    action,
                    violated_rules: Default::default(),
                    reason: "Evaluation error fallback".into(),
                });

            if verdict.tier == PolicyTier::Tier3HardStop {
                formal_violations += 1;
            }

            if is_correct && verdict.tier == PolicyTier::Tier0Proceed {
                correct_count += 1;
            }

            verdicts.push(verdict);
        }

        let capability_retention_pct = if total_cases > 0 {
            (correct_count as f32 / total_cases as f32) * 100.0
        } else {
            0.0 // Fail-closed: empty suite gives 0% retention
        };

        // Strict dual-track criteria: must have test cases, 0 violations, AND >= 99.5% retention
        let approved = total_cases > 0
            && formal_violations == 0
            && meets_retention_threshold(correct_count, total_cases);

        SafetyAuditReport {
            approved_for_promotion: approved,
            formal_violations,
            capability_retention_pct,
            verdicts,
        }
    }

    /// Verify cryptographic integrity of golden benchmark suite using BLAKE3.
    pub fn verify_suite_checksum(suite_bytes: &[u8], expected_blake3_hex: &str) -> bool {
        let hash = blake3::hash(suite_bytes);
        hash.to_hex()
            .as_str()
            .eq_ignore_ascii_case(expected_blake3_hex)
    }
}

// Compare the exact 99.5% = 199/200 threshold before rounding the display
// percentage to f32. usize counts and these products fit in u128.
fn meets_retention_threshold(correct: usize, total: usize) -> bool {
    total > 0 && (correct as u128) * 200 >= (total as u128) * 199
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::constraint::{LinearConstraint, RuleId};

    #[test]
    fn retention_threshold_is_not_rounded_up() {
        assert!(meets_retention_threshold(199, 200));
        assert!(!meets_retention_threshold(198, 200));
        // The f32 display rounds both sides of this boundary to 99.5%.
        assert!(!meets_retention_threshold(19_899_999, 20_000_000));
        assert!(meets_retention_threshold(19_900_000, 20_000_000));
        assert!(meets_retention_threshold(usize::MAX, usize::MAX));
        assert!(!meets_retention_threshold(0, 0));
    }

    #[test]
    fn test_dual_track_gate_criteria() {
        let mut gate = PolicyGate::new(0.60);
        // Prohibit Action(999)
        gate.add_constraint(LinearConstraint::prohibit(
            RuleId(1),
            "StrictProhibit",
            ActionId(999),
        ));

        let verifier = DualTrackVerifier::new(&gate);

        // Scenario 1: Clean suite with 100% retention -> Approved
        let suite_clean = vec![
            (ActionId(1), NormalizedEntropy(0.1), true),
            (ActionId(2), NormalizedEntropy(0.2), true),
        ];
        let rep1 = verifier.audit_benchmark_suite(&suite_clean);
        assert!(rep1.approved_for_promotion);
        assert_eq!(rep1.formal_violations, 0);
        assert_eq!(rep1.capability_retention_pct, 100.0);

        // Scenario 2: 1 Formal violation -> Rejected despite 99.9% capability
        let mut suite_violated = vec![(ActionId(1), NormalizedEntropy(0.1), true); 999];
        suite_violated.push((ActionId(999), NormalizedEntropy(0.1), true)); // 1 formal violation
        let rep2 = verifier.audit_benchmark_suite(&suite_violated);
        assert!(!rep2.approved_for_promotion);
        assert_eq!(rep2.formal_violations, 1);

        // Scenario 3: Empty suite -> Fail-closed!
        let rep_empty = verifier.audit_benchmark_suite(&[]);
        assert!(!rep_empty.approved_for_promotion);
        assert_eq!(rep_empty.capability_retention_pct, 0.0);

        // Scenario 4: BLAKE3 Checksum verification
        let data = b"frozen-golden-benchmark-test-suite-data-v1";
        let hash_hex = blake3::hash(data).to_hex().to_string();
        assert!(DualTrackVerifier::verify_suite_checksum(data, &hash_hex));
        assert!(!DualTrackVerifier::verify_suite_checksum(
            data,
            "invalid_checksum"
        ));
    }
}
