"""Gen-Zero Layer 5: Dual-Track Policy Gate & Tiered Escalation Middleware.

RFC Implementation for Issue #8 (Module 2):
1. Pure-function, zero-side-effect policy arbitration:
   evaluate_policy(decision, state, profile) -> PolicyGateVerdict
2. Hard Rules:
   - Regex pattern library matching irreversible/destructive/financial operations (delete, drop, pay, auth, etc.).
   - Blacklisted targets are blocked; whitelists cannot override policy rules.
   - Destructive operations are unconditional STOP; other sensitive operations require CONFIRM.
3. Soft Gate:
   - P(risk) >= tau_risk (default 0.20) is an unconditional STOP.
4. Tiered Confidence Escalation:
   - confidence < 0.30: STOP (blind guess protection).
   - 0.30 <= confidence < 0.50: ESCALATE (ambiguity fallback to System 2 / human).
   - confidence >= 0.50: PROCEED (autonomous clearance).
5. Domain-Adaptive Risk Profiles (READ_ONLY, STANDARD, CRITICAL).
"""

from dataclasses import dataclass, field, asdict
from enum import Enum
import re
import math
from numbers import Real
from typing import Any, Dict, List, Optional, Set, Union


class RiskLevel(str, Enum):
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"


class PolicyVerdictAction(str, Enum):
    PROCEED = "proceed"    # Safe for autonomous execution
    CONFIRM = "confirm"    # Requires explicit human/system confirmation
    ESCALATE = "escalate"  # Ambiguous/uncertain; route to System 2 / fallback
    STOP = "stop"          # Unsafe/blind guess; hard abort


@dataclass
class DomainRiskProfile:
    """Configures risk thresholds and whitelist for specific runtime domains."""
    name: str = "standard"
    min_proceed_confidence: float = 0.50
    min_escalate_confidence: float = 0.30
    risk_threshold: float = 0.20
    sensitive_patterns: List[str] = field(default_factory=lambda: [
        r"\b(delete|remove|rm|drop|truncate|destroy|wipe|kill|format)\b",
        r"\b(pay|payment|transfer|checkout|buy|purchase|withdraw|wire)\b",
        r"\b(sudo|chmod|chown|passwd|grant|revoke|authorize|secret|token)\b",
        r"\b(publish|broadcast|send_email|post_public)\b"
    ])
    whitelisted_targets: Set[str] = field(default_factory=set)
    blacklisted_targets: Set[str] = field(default_factory=set)

    @classmethod
    def read_only(cls) -> "DomainRiskProfile":
        """Relaxed profile for harmless read-only environments (search, calculator, view)."""
        return cls(
            name="read_only",
            min_proceed_confidence=0.40,
            min_escalate_confidence=0.25,
            risk_threshold=0.35,
            sensitive_patterns=[]
        )

    @classmethod
    def standard(cls) -> "DomainRiskProfile":
        """Balanced profile for standard web, workflow, and robotic automation."""
        return cls(name="standard")

    @classmethod
    def critical(cls) -> "DomainRiskProfile":
        """Strict zero-tolerance profile for financial, medical, or root infrastructure."""
        return cls(
            name="critical",
            min_proceed_confidence=0.65,
            min_escalate_confidence=0.45,
            risk_threshold=0.10
        )


@dataclass
class PolicyGateVerdict:
    """Decision outcome generated by the Dual-Track Policy Gate."""
    action: PolicyVerdictAction
    passed: bool
    requires_confirmation: bool
    confidence: float
    risk_score: float
    triggered_rules: List[str] = field(default_factory=list)
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "action": self.action.value,
            "passed": self.passed,
            "requires_confirmation": self.requires_confirmation,
            "confidence": round(self.confidence, 4),
            "risk_score": round(self.risk_score, 4),
            "triggered_rules": self.triggered_rules,
            "reason": self.reason,
            "metadata": self.metadata
        }


class DecisionPolicyGate:
    """Pure-function, zero-side-effect dual-track policy arbitration engine."""

    def __init__(self, default_profile: Optional[DomainRiskProfile] = None):
        self.default_profile = default_profile or DomainRiskProfile.standard()
        self._compiled_patterns: Dict[str, List[re.Pattern]] = {}

    def _get_compiled_patterns(self, profile: DomainRiskProfile) -> List[re.Pattern]:
        if profile.name not in self._compiled_patterns:
            self._compiled_patterns[profile.name] = [
                re.compile(pat, re.IGNORECASE) for pat in profile.sensitive_patterns
            ]
        return self._compiled_patterns[profile.name]

    def evaluate_policy(
        self,
        decision: Any,  # CompositeStepDecision or Dict
        state: Any = None,
        profile: Optional[DomainRiskProfile] = None
    ) -> PolicyGateVerdict:
        """Evaluates prospective decision against hard rules, soft probability, and confidence tiers.

        Required: action, target (nullable only for finish), risk/risk_prob,
        and confidence or both target_confidence/action_confidence. Probabilities
        must be finite numbers in [0, 1]; conflicting aliases are rejected.
        Context must be supplied via state, dict context, or state_feedback.

        Guaranteed pure function: does NOT mutate decision or state, does NOT perform I/O.
        """
        prof = profile or self.default_profile

        def reject(reason: str) -> PolicyGateVerdict:
            return PolicyGateVerdict(
                action=PolicyVerdictAction.STOP, passed=False,
                requires_confirmation=False, confidence=0.0, risk_score=1.0,
                triggered_rules=["INVALID_DECISION"], reason=reason,
                metadata={"profile": prof.name},
            )

        # Both supported representations require explicit evidence. No guessed
        # confidence/risk or action-as-target fallback is safe at this boundary.
        if isinstance(decision, dict):
            data = decision
        elif all(hasattr(decision, key) for key in (
            "target", "action", "target_confidence", "action_confidence", "risk_prob"
        )):
            data = {key: getattr(decision, key) for key in (
                "target", "action", "target_confidence", "action_confidence", "risk_prob"
            )}
            data["context"] = getattr(decision, "state_feedback", None)
        else:
            return reject("Unsupported or incomplete decision schema.")

        if state is None and data.get("context") is None:
            return reject("Decision requires context or an explicit state.")
        if "target" not in data or "action" not in data:
            return reject("Decision requires action and target fields.")
        action_str = data["action"]
        target = data["target"]
        if not isinstance(action_str, str) or not action_str.strip():
            return reject("Action must be a non-empty string.")
        if target is None:
            if action_str != "finish":
                return reject("Only finish may omit a target value.")
            target_str = ""
        elif not isinstance(target, str) or not target.strip():
            return reject("Target must be a non-empty string.")
        else:
            target_str = target
        if "action_type" in data and data["action_type"] != action_str:
            return reject("Conflicting action and action_type fields.")

        def probability(primary: str, alias: str) -> float:
            values = [data[key] for key in (primary, alias) if key in data]
            if not values:
                raise ValueError(f"Missing {primary} (or {alias}).")
            if any(isinstance(v, bool) or not isinstance(v, Real)
                   or not math.isfinite(v) or not 0.0 <= v <= 1.0 for v in values):
                raise ValueError(f"{primary} must be a finite number in [0, 1].")
            if any(v != values[0] for v in values):
                raise ValueError(f"Conflicting {primary} and {alias} fields.")
            return float(values[0])

        try:
            target_conf = probability("target_confidence", "confidence")
            action_conf = probability("action_confidence", "confidence")
            risk_p = probability("risk_prob", "risk")
        except (TypeError, ValueError, OverflowError) as exc:
            return reject(str(exc))

        if (isinstance(prof.risk_threshold, bool)
                or not isinstance(prof.risk_threshold, Real)
                or not math.isfinite(prof.risk_threshold)
                or not 0.0 <= prof.risk_threshold <= 1.0):
            return reject("Invalid profile risk threshold.")

        joint_conf = min(target_conf, action_conf)
        triggered_rules: List[str] = []

        # 1. Hard Rule: Target Blacklist Check
        if prof.blacklisted_targets and target_str in prof.blacklisted_targets:
            triggered_rules.append(f"TARGET_BLACKLISTED:{target_str}")
            return PolicyGateVerdict(
                action=PolicyVerdictAction.STOP,
                passed=False,
                requires_confirmation=False,
                confidence=joint_conf,
                risk_score=1.0,
                triggered_rules=triggered_rules,
                reason=f"Target entity '{target_str}' is explicitly blacklisted.",
                metadata={"profile": prof.name}
            )

        # Destructive operations are immutable hard stops, even in read-only
        # profiles with no configurable sensitive patterns or whitelisted targets.
        if re.search(r"\b(delete|remove|rm|drop|truncate|destroy|wipe|kill|format)\b",
                     f"{action_str} {target_str}", re.IGNORECASE):
            triggered_rules.append("DESTRUCTIVE_OPERATION")
        if risk_p >= prof.risk_threshold:
            triggered_rules.append(f"SOFT_RISK_BREACH:P(risk)={risk_p:.3f}>={prof.risk_threshold}")
        if triggered_rules:
            return PolicyGateVerdict(
                action=PolicyVerdictAction.STOP, passed=False,
                requires_confirmation=False, confidence=joint_conf,
                risk_score=risk_p, triggered_rules=triggered_rules,
                reason="Hard stop: destructive operation or risk threshold reached.",
                metadata={"profile": prof.name},
            )

        if joint_conf < prof.min_escalate_confidence:
            # Blind guessing zone (< 0.30)
            return PolicyGateVerdict(
                action=PolicyVerdictAction.STOP,
                passed=False,
                requires_confirmation=False,
                confidence=joint_conf,
                risk_score=risk_p,
                triggered_rules=["BLIND_GUESSING_ZONE"],
                reason=f"Confidence {joint_conf:.3f} is below minimum abort threshold {prof.min_escalate_confidence}.",
                metadata={"profile": prof.name}
            )

        # 2. Hard Rule: Sensitive Operation Regex Patterns
        # Match prospective action and target name; avoids false-positive halts from background state context
        combined_text = f"{action_str} {target_str}"
        patterns = self._get_compiled_patterns(prof)
        for p in patterns:
            match = p.search(combined_text)
            if match:
                matched_word = match.group(0)
                triggered_rules.append(f"HARD_PATTERN_MATCH:{matched_word}")

        # Sensitive operations still need confirmation; a whitelist never
        # supplies authorization or suppresses a policy rule.
        if triggered_rules:
            return PolicyGateVerdict(
                action=PolicyVerdictAction.CONFIRM,
                passed=False,
                requires_confirmation=True,
                confidence=joint_conf,
                risk_score=max(risk_p, 0.5),
                triggered_rules=triggered_rules,
                reason=f"Prospective operation requires confirmation: {', '.join(triggered_rules)}",
                metadata={"profile": prof.name}
            )

        # 5. Tiered Confidence Escalation
        if joint_conf < prof.min_proceed_confidence:
            # Ambiguity zone (0.30 <= conf < 0.50)
            return PolicyGateVerdict(
                action=PolicyVerdictAction.ESCALATE,
                passed=False,
                requires_confirmation=False,
                confidence=joint_conf,
                risk_score=risk_p,
                triggered_rules=["AMBIGUITY_ZONE"],
                reason=f"Confidence {joint_conf:.3f} is uncertain; escalating to System 2 / human supervisor.",
                metadata={"profile": prof.name}
            )
        else:
            # Certainty zone (>= 0.50) with no risk triggers
            return PolicyGateVerdict(
                action=PolicyVerdictAction.PROCEED,
                passed=True,
                requires_confirmation=False,
                confidence=joint_conf,
                risk_score=risk_p,
                triggered_rules=[],
                reason="Cleared all policy gates. Safe for autonomous execution.",
                metadata={"profile": prof.name}
            )
